name: Deploy Keras Model to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Create zip package (Lambda deployment package)
      - name: Create zip package
        run: zip -r lambda_function.zip . -x ".git/*"

      # Step 6: Deploy to AWS Lambda
      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name your-lambda-function-name \
            --zip-file fileb://lambda_function.zip

      # Step 7: (Optional) Update API Gateway (if needed)
      - name: Update API Gateway
        run: |
          aws apigateway update-integration \
            --rest-api-id your-api-id \
            --resource-id your-resource-id \
            --http-method POST \
            --integration-http-method POST \
            --type AWS \
            --uri arn:aws:apigateway:${{ secrets.AWS_REGION }}:lambda:path/2015-03-31/functions/arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:function:your-lambda-function-name/invocations \
            --credentials arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/your-api-gateway-role
