name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Triggers deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.9
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3) Install dependencies (adjust if you have no requirements.txt)
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4) Configure AWS Credentials
      - name: Configure AWS Credentials
        run: |
          export AKIASK5MCHV5CWSHNIQU=${{ secrets.AWS_ACCESS_KEY_ID }}
          export kaa3YkyhiBBS+cLnEpynLHU49nZPcdTXdpD62R2M=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=ap-south-1

      # 5) Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          EB_ENV_NAME: "Pancreatic-cancer-env"
          EB_APP_NAME: "pancreatic-cancer"
        run: |
          # Install the EB CLI
          pip install awsebcli
          
          # Initialize EB CLI for your application & platform
          eb init "$EB_APP_NAME" \
            --platform "64bit Amazon Linux 2023 running Python 3.9" \
            --region "$AWS_REGION"
          
          # Choose the correct environment
          eb use "$EB_ENV_NAME"
          
          # Deploy your latest changes
          eb deploy
